# Generated by Django 4.0.4 on 2022-05-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
