# Generated by Django 4.0.4 on 2022-05-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_products',
            new_name='featured_product_id',
        ),
    ]
