# Generated by Django 4.0.4 on 2022-05-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_featured_products_collection_featured_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product_id',
            new_name='featured_product',
        ),
    ]
