# Generated by Django 4.0.4 on 2022-05-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_featured_product_id_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='plcaed_at',
            new_name='placed_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
