# Generated by Django 4.0.4 on 2022-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_plcaed_at_order_placed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
