# Generated by Django 4.0.4 on 2022-05-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
